name: "Proyecto"

on:
  workflow_dispatch:
    inputs:
      input: 
        required: true
        description: '¿Que quieres imaginar?'
        type: string

jobs:
  generate-prompt:
    runs-on: ubuntu-latest
    steps:
      - name: "Generacion de Prompt con Gemini"
        uses: Drastyn/gemini/.gitub/actions/gemini-composite@main
        with: 
          prompt: ${{ inputs.input }}
          GH_TOKEN: ${{ secrets.PAT }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          
        
