name: "Proyecto"

on:
  workflow_dispatch:
    inputs:
      input: 
        required: true
        description: '¿Que quieres imaginar?'
        type: string

jobs:
  generate-prompt:
    runs-on: ubuntu-latest
    steps:
      - name: "Generacion de Prompt con Gemini"
        uses: Drastyn/gemini/.github/actions/gemini-composite@main
        with: 
          prompt: ${{ inputs.input }}
          output-artifact: 'prompt-created'
          GH_TOKEN: ${{ secrets.PAT }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          ATTEMPTS: ${{ vars.ATTEMPTS }}

  generate-image:
    runs-on: ubuntu-latest
    needs: generate-prompt
    steps:
      - name: "Crearcion de imagen con DALL-E-3"
        uses: Drastyn/create-image-gpt/.github/actions/create-image-gpt-composite@main
        with:
          GH_TOKEN: ${{ secrets.PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          input-artifact: 'prompt-created'
          prompt-file: 'output'
          ATTEMPTS: ${{ vars.ATTEMPTS }}
